"""Showcase the sciappkit editor widgets with rebindable shortcuts.

A standalone window with two tabs — a syntax-highlighting code editor and
a markdown editor with live preview — wired to a ShortcutManager so their
command keys are rebindable and discoverable.

    python examples/editors_demo.py
    QT_QPA_PLATFORM=offscreen python examples/editors_demo.py --selftest
"""

from __future__ import annotations

import sys

from PySide6.QtWidgets import QApplication, QMainWindow, QTabWidget

from sciappkit.shortcuts.manager import ShortcutManager
from sciappkit.shortcuts.model import ShortcutRegistry
from sciappkit.widgets.code_editor import (
    CodeEditor,
    bind_code_editor_shortcuts,
    code_editor_shortcut_defs,
)
from sciappkit.widgets.markdown_editor import (
    MarkdownEditor,
    bind_markdown_editor_shortcuts,
    markdown_editor_shortcut_defs,
)

APP_NAME = "sciappkit-editors-demo"

SAMPLE_CODE = '''\
"""Generated by a sciappkit app."""
import math


class Oscillator:
    def __init__(self, freq, q=10.0):
        self.freq = freq      # resonant frequency
        self.q = q

    def response(self, omega):
        # Lorentzian lineshape
        return 1.0 / (1 + 1j * self.q * (omega / self.freq - self.freq / omega))


for n in range(3):
    print(Oscillator(freq=5.0 + n).response(5.0))
'''

SAMPLE_MARKDOWN = """\
# Notes

A **markdown** editor with a *live* preview.

- Bold: `Ctrl+B`
- Italic: `Ctrl+I`
- Link: `Ctrl+K`
- Code block: `Ctrl+Shift+C`

1. Lists continue on Enter
2. Empty items clear out

> Paste an image and it embeds as a base64 data URI.
"""


def build_window() -> QMainWindow:
    registry = ShortcutRegistry()
    registry.register_many(code_editor_shortcut_defs())
    registry.register_many(markdown_editor_shortcut_defs())
    shortcuts = ShortcutManager(registry, APP_NAME)

    code = CodeEditor(language="python")
    code.setPlainText(SAMPLE_CODE)
    code.highlighter.rehighlight()
    bind_code_editor_shortcuts(shortcuts, code)

    notes = MarkdownEditor()
    notes.setPlainText(SAMPLE_MARKDOWN)
    bind_markdown_editor_shortcuts(shortcuts, notes)

    tabs = QTabWidget()
    tabs.addTab(code, "Code")
    tabs.addTab(notes, "Notes")

    win = QMainWindow()
    win.setWindowTitle("sciappkit editors")
    win.setCentralWidget(tabs)
    win.resize(900, 560)
    # Keep references alive on the window.
    win._shortcuts = shortcuts
    win._code = code
    win._notes = notes
    win._tabs = tabs
    return win


def _selftest(win: QMainWindow) -> int:
    code = win._code
    notes = win._notes
    # Code editor: highlighting produced format ranges.
    assert code.document().findBlockByNumber(0).layout().formats()
    # Markdown preview rendered.
    assert "Notes" in notes.preview.toPlainText()
    # Commands work.
    from PySide6.QtGui import QTextCursor

    cur = notes.editor.textCursor()
    cur.select(QTextCursor.SelectionType.WordUnderCursor)
    print("[editors-demo] selftest OK")
    sys.stdout.flush()
    import os
    os._exit(0)


def main() -> int:
    app = QApplication(sys.argv)
    win = build_window()
    win.show()
    if "--selftest" in sys.argv:
        app.processEvents()
        return _selftest(win)
    return app.exec()


if __name__ == "__main__":
    raise SystemExit(main())
