"""A full-featured sciappkit demo application.

Exercises most of the M1 surface in one app:

* a ``SciAppMainWindow`` with scene + matplotlib canvases (tabbed),
* dockable **Notes** (markdown editor with the web preview → inline images)
  and **Code** (syntax-highlighted) editors, their shortcuts bound to the
  app's ``ShortcutManager``,
* a **Settings** dialog (Ctrl+,) with theme, app fields, and a Shortcuts
  tab, all backed by a typed ``SettingsStore``,
* recent files, export (SVG/PNG/PDF), copy-to-clipboard, undo/redo, and a
  small JSON document model (notes + code).

    python examples/full_app.py
    QT_QPA_PLATFORM=offscreen python examples/full_app.py --selftest
"""

from __future__ import annotations

import json
import os
import sys

# QtWebEngine (the Notes web preview) needs the Chromium sandbox disabled in
# restricted/containerized/root environments. Harmless on a normal desktop.
# Must be set before QtWebEngine initializes.
os.environ.setdefault("QTWEBENGINE_DISABLE_SANDBOX", "1")
os.environ.setdefault(
    "QTWEBENGINE_CHROMIUM_FLAGS", "--no-sandbox --disable-gpu --disable-dev-shm-usage"
)

from PySide6.QtCore import Qt
from PySide6.QtGui import QAction, QBrush, QColor, QPen
from PySide6.QtWidgets import QApplication, QDockWidget

from sciappkit.app.main_window import SciAppMainWindow
from sciappkit.app.settings_dialog import SettingsDialog
from sciappkit.canvas.mpl_canvas import MplCanvas
from sciappkit.canvas.protocol import MplCanvasController, SceneCanvasController
from sciappkit.canvas.scene_canvas import GraphicsSceneBase, GraphicsViewBase
from sciappkit.settings.store import Setting, SettingsStore
from sciappkit.shortcuts.manager import ShortcutManager
from sciappkit.shortcuts.model import Shortcut, ShortcutRegistry
from sciappkit.shortcuts.overlay import ShortcutOverlayMixin, overlay_rows_from_registry
from sciappkit.widgets.code_editor import (
    CodeEditor,
    bind_code_editor_shortcuts,
    code_editor_shortcut_defs,
)
from sciappkit.widgets.markdown_editor import (
    MarkdownEditor,
    bind_markdown_editor_shortcuts,
    markdown_editor_shortcut_defs,
)

APP_NAME = "sciappkit-full-demo"

_MENU_SHORTCUTS = [
    Shortcut("file.new", default="Ctrl+N", category="File", display_name="New"),
    Shortcut("file.open", default="Ctrl+O", category="File", display_name="Open"),
    Shortcut("file.save", default="Ctrl+S", category="File", display_name="Save"),
    Shortcut("file.save_as", default="Ctrl+Shift+S", category="File", display_name="Save As"),
    Shortcut("file.export_png", default="Ctrl+E", category="File", display_name="Export PNG"),
    Shortcut("file.quit", default="Ctrl+Q", category="File", display_name="Quit"),
    Shortcut("edit.undo", default="Ctrl+Z", category="Edit", display_name="Undo"),
    Shortcut("edit.redo", default="Ctrl+Shift+Z", category="Edit", display_name="Redo"),
    Shortcut("edit.copy_as_image", default="Ctrl+Shift+C", category="Edit", display_name="Copy as Image"),
    Shortcut("edit.preferences", default="Ctrl+,", category="Edit", display_name="Preferences"),
    Shortcut("view.fit", default="Ctrl+0", category="View", display_name="Fit to Content"),
    Shortcut("view.zoom_in", default="Ctrl++", category="View", display_name="Zoom In"),
    Shortcut("view.zoom_out", default="Ctrl+-", category="View", display_name="Zoom Out"),
    Shortcut(
        "overlay.toggle", default="?", category="Help",
        display_name="Toggle Shortcut Hints", is_single_key=True, is_menu_action=True,
    ),
]

SAMPLE_CODE = '''\
"""Generated by the sciappkit full demo."""
import numpy as np


def lorentzian(omega, omega0, q):
    return 1.0 / (1 + 1j * q * (omega / omega0 - omega0 / omega))


omega = np.linspace(4, 6, 11)
print(np.abs(lorentzian(omega, 5.0, 10.0)))
'''

SAMPLE_NOTES = """\
# Project notes

This app is built entirely from **sciappkit**:

- canvases (scene + matplotlib)
- a code editor with syntax highlighting
- this markdown editor with a **web preview** (inline images work!)
- a Settings dialog (`Ctrl+,`) with theme + shortcuts

Pasted images become clean references, not giant base64 blobs:

![diagram](attachment:diagram)

> Tip: paste or drop an image — the source stays readable.
"""


def _demo_image_bytes() -> bytes:
    """A small PNG used to seed the notes attachment (needs a QApplication)."""
    from PySide6.QtCore import QBuffer, QIODevice
    from PySide6.QtGui import QColor, QImage, QPainter

    img = QImage(120, 70, QImage.Format.Format_ARGB32)
    img.fill(QColor(120, 170, 255))
    painter = QPainter(img)
    painter.setPen(QColor(30, 60, 120))
    painter.drawText(img.rect(), 0x84, "sciappkit")  # AlignCenter
    painter.end()
    buf = QBuffer()
    buf.open(QIODevice.OpenModeFlag.WriteOnly)
    img.save(buf, "PNG")
    return bytes(buf.data())


def _build_settings() -> SettingsStore:
    schema = [
        Setting("theme", "system", section="theme", key="mode"),
        Setting("code_theme", "auto"),
        Setting("grid_spacing", 20.0, section="grid", key="spacing"),
        Setting("snap_to_grid", True),
        Setting("routing", "ortho"),
        Setting("recent_files", [], mutable=True),
        Setting("last_directory", ""),
    ]
    return SettingsStore(APP_NAME, schema)


def _build_shortcuts() -> ShortcutManager:
    reg = ShortcutRegistry()
    reg.register_many(_MENU_SHORTCUTS)
    reg.register_many(markdown_editor_shortcut_defs())
    reg.register_many(code_editor_shortcut_defs())
    mgr = ShortcutManager(reg, APP_NAME)
    mgr.load()
    return mgr


def _build_scene_controller():
    scene = GraphicsSceneBase()
    scene.addRect(0, 0, 160, 100, QPen(QColor(40, 40, 40), 2), QBrush(QColor(120, 170, 255)))
    scene.addEllipse(40, 130, 120, 80, QPen(QColor(40, 40, 40), 2), QBrush(QColor(255, 200, 120)))
    view = GraphicsViewBase(scene)
    return SceneCanvasController(view), view


def _build_mpl_controller():
    canvas = MplCanvas(show_axes=True)
    canvas.ax.plot([4, 4.5, 5, 5.5, 6], [0.2, 0.5, 1.0, 0.5, 0.2], marker="o")
    canvas.ax.set_title("|response|")
    return MplCanvasController(canvas)


class FullWindow(SciAppMainWindow, ShortcutOverlayMixin):
    def __init__(self):
        self._scene_ctrl, self._scene_view = _build_scene_controller()
        self._mpl_ctrl = _build_mpl_controller()
        super().__init__(
            "sciappkit full demo",
            _build_settings(),
            _build_shortcuts(),
            [self._scene_ctrl, self._mpl_ctrl],
        )
        self._build_editor_docks()
        self._apply_settings()
        # On-canvas shortcut cheat sheet (press "?" or use Help ▸ Toggle
        # Shortcut Hints). Rows come straight from the registry, so any
        # rebinding in Settings is reflected automatically.
        self.init_shortcut_overlay(corner="top-right", enabled=False)
        # Keep the editors in sync with light/dark chrome changes: re-resolve
        # an "auto" code theme, and re-render the notes preview so its CSS
        # picks up the new palette.
        self.theme_changed.connect(lambda _mode: self.code.set_theme(self._settings.code_theme))
        self.theme_changed.connect(lambda _mode: self.notes.refresh_preview())

    # -- docks --------------------------------------------------------------

    def _build_editor_docks(self) -> None:
        self.notes = MarkdownEditor(backend="web")
        # Seed an attachment so the notes reference it cleanly (no base64 blob).
        self.notes.editor.attachments["diagram"] = (_demo_image_bytes(), "image/png")
        self.notes.setPlainText(SAMPLE_NOTES)
        bind_markdown_editor_shortcuts(self._shortcuts, self.notes)
        notes_dock = QDockWidget("Notes", self)
        notes_dock.setWidget(self.notes)
        self.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, notes_dock)
        self._notes_dock = notes_dock

        self.code = CodeEditor(language="python", theme=self._settings.code_theme)
        self.code.setPlainText(SAMPLE_CODE)
        self.code.highlighter.rehighlight()
        bind_code_editor_shortcuts(self._shortcuts, self.code)
        code_dock = QDockWidget("Code", self)
        code_dock.setWidget(self.code)
        self.addDockWidget(Qt.DockWidgetArea.BottomDockWidgetArea, code_dock)
        self._code_dock = code_dock

        # The Tools menu was created during the base __init__ (before the
        # docks existed); add the dock toggles now.
        self._tools_menu.addSeparator()
        self._tools_menu.addAction(notes_dock.toggleViewAction())
        self._tools_menu.addAction(code_dock.toggleViewAction())

    # -- menus --------------------------------------------------------------

    def populate_extra_menus(self, menubar) -> None:
        self._tools_menu = menubar.addMenu("&Tools")
        self._add_action(self._tools_menu, "&Preferences…", self.open_preferences, "edit.preferences")

        help_menu = menubar.addMenu("&Help")
        # A single-key ("?") *menu* action, so Qt routes it to a focused text
        # field instead of firing the overlay while typing in the editors.
        self._add_action(
            help_menu, "Keyboard Shortcut &Hints",
            self.toggle_shortcut_overlay, "overlay.toggle", checkable=True,
        )

    # -- shortcut overlay ---------------------------------------------------

    def shortcut_overlay_host(self):
        return self._scene_view

    def shortcut_overlay_rows(self):
        rows = overlay_rows_from_registry(self._shortcuts.registry)
        return ("Keyboard shortcuts", rows)

    # -- settings -----------------------------------------------------------

    def build_settings_dialog(self) -> SettingsDialog:
        from sciappkit.widgets.highlight_theme import list_themes

        dlg = SettingsDialog(self._settings, self._shortcuts, self)
        dlg.add_double("grid_spacing", "Grid spacing", minimum=2, maximum=200, step=1)
        dlg.add_bool("snap_to_grid", "Snap to grid")
        dlg.add_choice("routing", "Routing", ["ortho", "direct", "curved"])
        dlg.add_choice("code_theme", "Code theme", ["auto", *list_themes()])
        dlg.applied.connect(self._apply_settings)
        return dlg

    def open_preferences(self) -> None:
        self.build_settings_dialog().exec()

    def _apply_settings(self) -> None:
        self._scene_view.grid_spacing = float(self._settings.grid_spacing)
        self._scene_view.snap_enabled = bool(self._settings.snap_to_grid)
        self.apply_theme(self._settings.theme)
        self.code.set_theme(self._settings.code_theme)

    # -- document model (notes + code as JSON) ------------------------------

    def do_new(self) -> None:
        self.notes.setPlainText("")
        self.code.setPlainText("")

    def do_open(self, path: str) -> bool:
        try:
            data = json.loads(open(path, encoding="utf-8").read())
        except (OSError, ValueError):
            return False
        # Notes carry text + attachments (images kept out of the source).
        self.notes.load_document(data.get("notes", {"text": ""}))
        self.code.setPlainText(data.get("code", ""))
        return True

    def do_save(self, path: str) -> bool:
        try:
            with open(path, "w", encoding="utf-8") as f:
                json.dump({"notes": self.notes.document(), "code": self.code.toPlainText()}, f)
        except OSError:
            return False
        return True


def build_window() -> FullWindow:
    win = FullWindow()
    win.resize(1100, 720)
    return win


def _selftest(win: FullWindow) -> int:
    import tempfile
    from pathlib import Path

    out = Path(tempfile.mkdtemp(prefix="sciappkit-full-"))
    # Save + reopen the document model.
    doc = out / "doc.json"
    assert win.do_save(str(doc)) and doc.exists()
    win.do_new()
    assert win.notes.toPlainText() == ""
    assert win.do_open(str(doc))
    assert "Project notes" in win.notes.toPlainText()

    # Settings dialog builds and applies.
    dlg = win.build_settings_dialog()
    dlg.apply()

    # Export the active canvas.
    ctrl = win.active_controller()
    ctrl.exporter.export_png(ctrl.export_target(), str(out / "canvas.png"))
    assert (out / "canvas.png").exists()

    # Shortcut overlay: toggling on populates rows from the registry and shows.
    assert not win.shortcut_overlay_enabled
    win.toggle_shortcut_overlay()
    assert win.shortcut_overlay_enabled and win.shortcut_overlay.isVisible()
    win.toggle_shortcut_overlay()
    assert not win.shortcut_overlay_enabled and not win.shortcut_overlay.isVisible()

    print(f"[full-demo] selftest OK — artifacts in {out}")
    sys.stdout.flush()
    import os
    os._exit(0)


def main() -> int:
    # QtWebEngine requires shared OpenGL contexts, set before the app exists.
    QApplication.setAttribute(Qt.ApplicationAttribute.AA_ShareOpenGLContexts)
    app = QApplication(sys.argv)
    win = build_window()
    win.show()
    if "--selftest" in sys.argv:
        app.processEvents()
        return _selftest(win)
    return app.exec()


if __name__ == "__main__":
    raise SystemExit(main())
